### PR TITLE
update news page

### PR DESCRIPTION
**Pull request by JustinWarden**
i have updated the keanu reeves news page

### CODE REVIEW

**Comment by calebooski13** [comment]
Couldn't view page, file name does not match the link. Try changing file name to just news

**Comment by kelli-evans09** [comment]
-Couldn't view page because file names do not match the link.

-Try changing html page to news.html OR change the navbar link to jw-news.html

**Comment by JustinWarden** [comment]
i have fixed the bug

**Comment by calebooski13** [comment]
bodacious, looks great

**Comment by kelli-evans09** [comment]
Looks great!

**Pull request merged**
